### ISSUE TITLE
react native app brakes when calling agent.init()

### ISSUE THREAD

**Issue by proteche** [TimoGlastra/aries-mobile-agent-react-native#2]
react native app brakes without any error,
`await agent.init();` 
File: /src/App.tsx line no:32

can u please give some information,
1) which mediator supports this project (.net,go)?
2) is genesis file needed to connect with mediator?

**Comment by TheArhaam** [comment]
@proteche To successfully complete the Agent initialization you will need to start a mediator. 
Pull the [aries-framework-javascript](https://github.com/hyperledger/aries-framework-javascript/) repo and start the test mediators (can easily be done using Docker)
Once the mediator is up, update the mediator URL on [this line](https://github.com/TimoGlastra/aries-mobile-agent-javascript/blob/master/src/agentInit.ts#L129).

**Comment by proteche** [comment]
@TheArhaam  its still brakes without any errors.
1) this function seems unused, anything to do with this function [this line](https://github.com/TimoGlastra/aries-mobile-agent-javascript/blob/31b567674e15b1627fa2e097a807f3a801315f17/src/agentInit.ts#L44) 
2) any idea about how mediator connects with mobile agent 
3) whats /invitation endpoint in mediator?

**Comment by TheArhaam** [comment]
@proteche May I know the steps you took to start the mediator?

1. It is used, when the agent is initialized the `start()` function of `PollingInboundTransporter` is called which further invokes the `registerMediator()` function.
2. The Agent establishes the connection with the Mediator, the `registerMediator()` function contains the code for this.
3. The `/invitation` endpoint returns the invitation object which is used to establish a connection between the Mediator & Mobile Agent.

**Comment by proteche** [comment]
steps to start mediator 
```
1) git clone https://github.com/hyperledger/aries-framework-javascript.git  # Clone the repo
2) cd aries-framework-javascript
3) docker-compose up -d # Run alice-mediator and bob-mediator
```
this is what `/invitation` endpoint returns 
`https://example.com/ssi?c_i=eyJAdHlwZSI6ImRpZDpzb3Y6QnpDYnNOWWhNcmpIaXFaRFRVQVNIZztzcGVjL2Nvbm5lY3Rpb25zLzEuMC9pbnZpdGF0aW9uIiwiQGlkIjoiN2QwNzE3NjMtM2YwNC00MzFlLWI2YWYtZmZjNTc5ZmNiNDNiIiwibGFiZWwiOiJSb3V0aW5nTWVkaWF0b3IwMSIsInJlY2lwaWVudEtleXMiOlsiQlJ0Q2NZbXVNU3hHczJvVDlNRnM4NnBIaVpBVERua0ZGYXllNWd3aVZSSE4iXSwic2VydmljZUVuZHBvaW50IjoiaHR0cDovL2xvY2FsaG9zdDozMDAxL21zZyIsInJvdXRpbmdLZXlzIjpbXX0`

**Comment by proteche** [comment]
@TheArhaam  anything wrong with above steps?

**Comment by TheArhaam** [comment]
@proteche There doesn't seem to be anything wrong with the steps, It could be that the app is facing an issue after the agent is initialized, most probably when a message is being sent to the Mediator. I will get back to you with more details.

**Comment by TheArhaam** [comment]
@proteche Please update the AGENT_URL before starting the Mediators: https://github.com/hyperledger/aries-framework-javascript/blob/master/run.sh#L7 & https://github.com/hyperledger/aries-framework-javascript/blob/master/run.sh#L15

**Comment by TimoGlastra** [comment]
@proteche #4 should make the process a bit more straightforward

**Comment by proteche** [comment]
@TimoGlastra ngrok works nicely.
@TheArhaam the error still persist

<img src="https://user-images.githubusercontent.com/62335562/101450564-ba423480-3950-11eb-90d4-77d4d37cfbf6.png"  width="220" height="400" /> <img src="https://user-images.githubusercontent.com/62335562/101450999-726fdd00-3951-11eb-995e-0a76d7e8533a.png"  width="220" height="200" />

**Comment by TimoGlastra** [comment]
The error doesn't give much detail. Could you give a step-by-step reproduction of the steps you took?

From aries-framework-javascript setup all the way to making changes to and running the app

**Comment by proteche** [comment]
@TimoGlastra okay, its get stuck when calling this endpoint `/msg` [this line](https://github.com/TimoGlastra/aries-mobile-agent-react-native/blob/85a2ae6f7c7231b91a1cd00726a7d155d8492d4e/src/agentInit.ts#L90)

and ends up by giving the error `Network request failed`

**Comment by TheArhaam** [comment]
@proteche It's possible that the `endpoint` is `localhost:3001/msg` which is what caused the issue for me previously. Could you check?

**Comment by proteche** [comment]
**steps to reproduce**

```
git clone https://github.com/TimoGlastra/aries-framework-javascript.git
checkout docker-mediators-ngrok
cd aries-framework-javascript
```

**Setup Ledger**
```
# Build indy pool
docker build -f network/indy-pool.dockerfile -t indy-pool .

# Start indy pool
docker run -d --rm --name indy-pool -p 9701-9708:9701-9708 indy-pool

# Setup CLI. This creates a wallet, connects to the ledger and sets the Transaction Author Agreement
docker exec indy-pool indy-cli-setup

#  DID and Verkey from seed
docker exec indy-pool add-did-from-seed 000000000000000000000000Trustee9
```
**Usage with Docker**
```
docker build -t aries-framework-javascript .

# Run tests without network
docker run -it --rm aries-framework-javascript  yarn test -t "agents"

# Run test with mediator agents and ledger pool
docker-compose -f docker/docker-compose-mediators.yml -f docker/docker-compose-mediators-ngrok.yml up -d
docker run --rm --network host --env TEST_AGENT_PUBLIC_DID_SEED=000000000000000000000000Trustee9 --env GENESIS_TXN_PATH=network/genesis/local-genesis.txn --env DEBUG=aries-framework-javascript aries-framework-javascript yarn test

```

**Comment by proteche** [comment]
@TheArhaam  nope the endpoint is `https://7856ecd363a8.ngrok.io:3001/msg`

error `sending message {"line":26807,"column":33,"sourceURL":"http://localhost:8081/index.bundle?platform=android&dev=true&minify=false"}`

**Comment by TheArhaam** [comment]
@proteche I don't think the ngrok support has been merged yet 
https://github.com/hyperledger/aries-framework-javascript/pull/139

For now, you will have to manually add your IP Address in `./run.sh` 
https://github.com/hyperledger/aries-framework-javascript/blob/master/run.sh

**Comment by proteche** [comment]
Thanks @TheArhaam it works without ngrok.

**Comment by TimoGlastra** [comment]
@proteche When using ngrok you must remove the port (`3001`). Ngrok uses 80/443 and maps that to the port.

**Comment by proteche** [comment]
@TheArhaam any sample invitation url to test accept connection?

**Comment by TheArhaam** [comment]
@proteche You can install the app on two devices and form a connection between them. 
Also, is your ngrok issue resolved?

**Comment by proteche** [comment]
@TheArhaam i didn't tested yet but as TimoGlastra suggest to remove port from such url
`https://7856ecd363a8.ngrok.io:3001/msg`
it should work then...
is it possible, this to work with framework like `aries-cloudagent-python ` as well?

**Comment by proteche** [comment]
@TimoGlastra @TheArhaam do you guys have any plan to extend this app to support storing verifiable credentials?
